version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/frontend
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: ["certbot", "certonly", "--webroot", "--webroot-path=/var/www/certbot", "--email", "contato@metalgest.com.br", "--agree-tos", "--no-eff-email", "--keep-until-expiring", "--domains", "metalgest.com.br,www.metalgest.com.br"]
    depends_on:
      - nginx

volumes:
  postgres_data:
  certbot_certs:
  certbot_www:

networks:
  app-network:
    driver: bridge
