services:
  # Novo Backend Node.js + SQLite3
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3010
      DATABASE_PATH: /app/data/sqlite.db
      JWT_SECRET: ${JWT_SECRET:-metalgest-jwt-secret-production}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-metalgest-refresh-secret-production}
      FRONTEND_URL: ${FRONTEND_URL:-http://72.60.10.112:3002}
    ports:
      - "3010:3010"
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - metalgest-network

  # Frontend React/Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://72.60.10.112:3010/api}
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - metalgest-network

  # Nginx Proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "3002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - metalgest-network

networks:
  metalgest-network:
    driver: bridge